spring:
  application:
    name: restexam

  datasource:
    url:  jdbc:mariadb://localhost:3306/jpadb
    username: jiyun
    password: 1010
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true