spring:
  application:
    name: restexam

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 4MB

  datasource:
    url:  jdbc:mariadb://localhost:3306/jpadb
    username: jiyun
    password: 1010
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: true